version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - API_PROXY_TARGET=http://backend:${BACKEND_PORT}
      - PORT=${FRONTEND_PORT}
    links:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}